Ej/background maps settings flag
digidem/mapeo-desktop pull request #737
Opened 2023-07-12 13:57 UTC by lightlii

Adds 'Experiments' list to settings menu with `Background Maps` as (currently only) option.
When Background Maps flag is activated, Background maps becomes an available option in settings.

closes https://github.com/digidem/mapeo-desktop/issues/733

## Preview

![Screenshot from 2023-07-17 12-33-16](https://github.com/digidem/mapeo-desktop/assets/32508751/50677245-ce32-488c-b385-b8f7070cf80f)
![Screenshot from 2023-07-17 12-33-10](https://github.com/digidem/mapeo-desktop/assets/32508751/214870db-a0be-4aa5-b08c-404c0a6e3b23)
![Screenshot from 2023-07-17 12-33-25](https://github.com/digidem/mapeo-desktop/assets/32508751/db4a8c64-05a8-47a8-8adc-765db1adfdb5)

2023-07-19 22:05 UTC, ErikSin requested changes
Good job! I left some minor comments/suggestions

2 things:
1. Once you rebase/merge from master, I would like to give it one more quick look before you merge.
2. I added alot of maps in testing. When it is loading the list of maps, it blocks the UI. I think that is fine when it is initially loading, but Tan stack query makes the API call everytime the window is out of focus and refocused, causing the UI to be blocked. I think we should [disable invalidating the query](https://tanstack.com/query/v4/docs/react/guides/disabling-queries). And when the users uploads a new map, we can use the `refetch` function to refresh the list. That way the list is not constantly trying to refetch even when we know there is no new data.

2023-07-26 14:51 UTC, lightlii commented on src/renderer/components/dialogs/ImportMapStyle.js
> +          <CardActionArea style={{ backgroundColor: '#EDEDED', padding: 30 }} onClick={selectMbTileFile}>
Yep, I'd copied over the code from the prev PR, it was using electron `remote` which no longer works.

Fixed now!

2023-07-26 15:55 UTC, lightlii commented
Hey I think I've added what you requested in (2) in your comment above. So it's ready to look at again I'd say!

2023-07-26 15:56 UTC, lightlii commented
Oops sorry, nope I missed error handling in `ImportMapStyle`, I can finish that up first thing tomorrow

2023-07-27 12:43 UTC, lightlii commented
@ErikSin I've rebased from master, so this is ready for a last look over

2023-08-02 21:49 UTC, ErikSin commented
Im unable to open it. Are you able to open it on your local device?

2023-08-07 13:31 UTC, lightlii commented
> Im unable to open it. Are you able to open it on your local device?

I don't have any issues running it. Lets look at that together when we call later

2023-08-09 19:29 UTC, ErikSin commented
There are some import errors that the linter and vs code are catching

2023-08-28 15:32 UTC, lightlii commented
These changes are in #744 so @ErikSin & I agreed to close and only review #744

2023-08-28 15:32 UTC, closed without merging